import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button } from './style'
import { Overidebutton } from './style'
import Link from 'next/link'
export default function Home() {
  return (
    
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button>Normal Button</Button>
    <Button primary>Primary Button</Button>
    <Overidebutton>Overidebutton</Overidebutton> */}
    <ul>
      <Link href="/hello"><li>hello</li></Link>
      <li>bye</li>
      <li>cya</li>
    </ul>
          </div>
  )
}
